# Overrides from https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
  ExtraDetails: true
  TargetRubyVersion: 2.4
  TargetRailsVersion: 4.2
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Send:
  Enabled: true

Style/SingleLineMethods:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/VariableNumber:
  Enabled: false

Style/WhileUntilModifier:
  MaxLineLength: 80

##################### Metrics ##################################

Metrics/AbcSize:
  Max: 19

Metrics/BlockLength:
  Max: 150
  Exclude:
    - 'app/admin/**/*'
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'test/**/*'

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  Max: 120

Metrics/ModuleLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 8

##################### Lint ##################################

Lint/AmbiguousBlockAssociation:
  Enabled: false

##################### Performance ############################

# Using all defaults

##################### Rails ##################################

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/Output:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb
    - test/**/*.rb

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
