# Overrides from https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
  ExtraDetails: true
  TargetRubyVersion: 2.4
  TargetRailsVersion: 4.2
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Naming/VariableNumber:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Send:
  Enabled: true

Style/SingleLineMethods:
  Enabled: false

Style/SymbolArray:
  Enabled: true

##################### Metrics ##################################

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 150
  Exclude:
    - 'app/admin/**/*'
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'test/**/*'

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  Max: 175

Metrics/ModuleLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Max: 135

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 15

##################### Lint ##################################

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

##################### Performance ############################

# Using all defaults

##################### Rails ##################################

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/Output:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb
    - test/**/*.rb

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
