FROM ruby:2.5.7

WORKDIR /complect

RUN apt-get update -yqq && apt-get install -yqq --no-install-recommends \
  postgresql-client \
  build-essential \
  libreoffice \
  wkhtmltopdf

ENV NODE_VERSION=14.17.3
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version

ENV NODE_OPTIONS=--max_old_space_size=4096

RUN gem install bundler

COPY Gemfile* ./
RUN bundle install --without development test

RUN curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0 && \
  ln -sf $HOME/.yarn/bin/yarn /usr/local/bin/yarn && \
  ln -sf $HOME/.yarn/bin/yarnpkg /usr/local/bin/yarnpkg

COPY . .

RUN bundle exec rake assets:precompile

CMD bundle exec puma -C config/puma.rb
