version: '3.6'

volumes:
  redis:

services:
  redis:
    image: 'redis:latest'
    command: redis-server
    volumes:
      - 'redis:/data'
  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/app'
    env_file:
      - '.env.local'
  web:
    env_file:
      - '.env.local'
    build: .
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    depends_on:
      - 'sidekiq'

