version: v1.0
name: Deploy to production
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    task:
      secrets:
        - name: docker-hub
      env_vars:
        - name: HEROKU_APP
          value: docker-production
        - name: RACK_ENV
          value: production
        - name: RAILS_ENV
          value: production
      jobs:
        - name: 'Deploy PROD'
          commands:
            - checkout
            - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            - docker pull "$DOCKER_USERNAME"/docker-hub:$SEMAPHORE_WORKFLOW_ID
            - docker images
            - heroku container:login
            - docker tag "$DOCKER_USERNAME"/docker-hub:$SEMAPHORE_WORKFLOW_ID registry.heroku.com/$HEROKU_APP/web
            - heroku stack:set container --app $HEROKU_APP
            - docker push registry.heroku.com/$HEROKU_APP/web
            - heroku container:release web --app $HEROKU_APP
            - heroku run --exit-code -- bundle exec rake db:migrate
